version: '3'
services:
  mongodb:
    container_name: mongodb
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: acrleomozzer.azurecr.io/mongodb:latest
    environment:
      MONGO_INITDB_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: acrleomozzer.azurecr.io/backend:latest
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "80:80"
    depends_on:
      - mongodb
    environment:
      MONGODB_HOST: ''
      MONGO_INITDB_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      NODE_ENV: development
      JWT_TOKEN: 'ABC123456'
      JWT_TOKEN_EXPIRATION_SECONDS: '144000s'
      APP_PORT: 80

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "80:80"